-- =============================================================================
-- GSM-14 MVP — Bước 2/3: 16 bảng dữ liệu, khoá ngoại và index
-- Nguồn: docs/database-spec.md
--
-- NGUYÊN TẮC: chỉ ràng buộc những gì spec nói thẳng.
--   - CHECK giá trị chỉ đặt khi spec liệt kê đúng các mã đó.
--   - Cột trạng thái spec không nêu mã nào => VARCHAR tự do, không CHECK,
--     không DEFAULT. Thêm CHECK sau khi nhóm chốt từ vựng.
--   - Không thêm ràng buộc "cho chắc" (amount >= 0, batch_size > 0, ...).
--
-- Thứ tự tạo bảng tuân theo phụ thuộc khoá ngoại. Ràng buộc duy nhất đi ngược
-- chiều (supply_demand_cells -> campaigns) được thêm bằng ALTER ở cuối file.
-- =============================================================================

set search_path = public, extensions;

-- =============================================================================
-- NHÓM 1 — Tài khoản, tài xế và bản đồ
-- =============================================================================

-- 1. profiles ----------------------------------------------------------------
create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  -- Spec §2 liệt kê đúng hai vai trò.
  role         varchar(20)  not null check (role in ('OPERATOR', 'DRIVER')),
  full_name    text,
  phone        varchar(20),
  avatar_url   text,
  is_active    boolean      not null default true,
  created_at   timestamptz  not null default now(),
  updated_at   timestamptz  not null default now()
);

comment on table public.profiles is
  'Hồ sơ mở rộng từ Supabase Auth. FK trung tâm cho tài xế, người duyệt và người tạo campaign.';

create index idx_profiles_role on public.profiles (role) where is_active;

-- 2. h3_cells ----------------------------------------------------------------
create table public.h3_cells (
  h3_index       varchar(20) primary key,
  -- 0..15 là định nghĩa của hệ H3, không phải suy đoán về thiết kế.
  resolution     smallint    not null check (resolution between 0 and 15),
  district_code  varchar(20),
  district_name  text,
  center_point   geography(Point, 4326),
  boundary       geography(Polygon, 4326),
  is_active      boolean     not null default true
);

comment on table public.h3_cells is
  'Danh mục cell lục giác cố định (Hà Nội) dùng cho heatmap và lọc không gian nhanh.';

create index idx_h3_cells_district  on public.h3_cells (district_code) where is_active;
create index idx_h3_cells_boundary  on public.h3_cells using gist (boundary);
create index idx_h3_cells_center    on public.h3_cells using gist (center_point);

-- =============================================================================
-- NHÓM 2 — Cung–cầu
-- =============================================================================

-- 3. supply_demand_snapshots -------------------------------------------------
create table public.supply_demand_snapshots (
  id             bigint      generated by default as identity primary key,
  captured_at    timestamptz not null,
  data_source    varchar(30),
  scenario_code  varchar(50),
  total_demand   integer,
  total_supply   integer,
  created_at     timestamptz not null default now()
);

comment on table public.supply_demand_snapshots is
  'Header của mỗi lần persist cung–cầu. Nguồn tổng hợp cho heatmap, model_inputs, hotspot và proposal.';

create index idx_snapshots_captured_at on public.supply_demand_snapshots (captured_at desc);

-- 4. supply_demand_cells -----------------------------------------------------
create table public.supply_demand_cells (
  snapshot_id         bigint      not null references public.supply_demand_snapshots (id) on delete cascade,
  h3_index            varchar(20) not null references public.h3_cells (h3_index),
  current_demand      integer,
  predicted_demand    integer,
  available_supply    integer,
  -- Spec không định nghĩa công thức gap => cột thường, backend tự ghi.
  demand_supply_gap   integer,
  -- Spec chỉ nhắc tới ORANGE/RED, không liệt kê đủ thang => chưa đặt CHECK.
  severity_level      varchar(20),
  -- FK tới campaigns được thêm bằng ALTER ở cuối file.
  active_campaign_id  uuid,
  primary key (snapshot_id, h3_index)
);

comment on table public.supply_demand_cells is
  'Chỉ số cung–cầu theo snapshot × H3 cell. Nguồn dữ liệu chính của heatmap hiện tại.';

create index idx_sd_cells_h3       on public.supply_demand_cells (h3_index);
create index idx_sd_cells_severity on public.supply_demand_cells (snapshot_id, severity_level);

-- =============================================================================
-- NHÓM 3 — Phát hiện và ra quyết định
-- =============================================================================

-- 5. hotspots ----------------------------------------------------------------
create table public.hotspots (
  id                   uuid        primary key default gen_random_uuid(),
  snapshot_id          bigint      references public.supply_demand_snapshots (id) on delete set null,
  -- Spec không liệt kê mã trạng thái hotspot => chưa đặt CHECK/DEFAULT.
  status               varchar(30),
  affected_h3_indexes  text[],
  geofence             geography(Polygon, 4326),
  shortage_count       integer,
  severity_level       varchar(20),
  cause_code           varchar(50),
  expected_start_at    timestamptz,
  expected_end_at      timestamptz,
  detected_at          timestamptz not null default now(),
  resolved_at          timestamptz
);

comment on table public.hotspots is
  'Vùng thiếu xe được phát hiện từ snapshot hoặc kết quả Model. Đầu vào để tạo proposal.';

create index idx_hotspots_detected on public.hotspots (detected_at desc);
create index idx_hotspots_status   on public.hotspots (status, detected_at desc);
create index idx_hotspots_snapshot on public.hotspots (snapshot_id);
create index idx_hotspots_h3       on public.hotspots using gin (affected_h3_indexes);
create index idx_hotspots_geofence on public.hotspots using gist (geofence);

-- 6. proposals ---------------------------------------------------------------
create table public.proposals (
  id                   uuid         primary key default gen_random_uuid(),
  hotspot_id           uuid         references public.hotspots (id) on delete set null,
  input_snapshot_id    bigint       references public.supply_demand_snapshots (id) on delete set null,

  -- Versioning: spec yêu cầu "giữ version, không ghi đè proposal đã duyệt".
  root_proposal_id     uuid         references public.proposals (id) on delete set null,
  parent_proposal_id   uuid         references public.proposals (id) on delete set null,
  version              integer,

  -- Spec §4.3 liệt kê đúng bốn nguồn sinh phương án.
  generator_type       varchar(20)  not null
                         check (generator_type in ('MOCK', 'RULE_BASED', 'AGENT', 'MANUAL')),
  generator_version    varchar(50),

  -- Spec nhắc APPROVED/REJECTED nhưng không liệt kê đủ vòng đời => chưa CHECK.
  status               varchar(30),
  policy_status        varchar(30),

  target_h3_indexes    text[],
  target_geofence      geography(Polygon, 4326),

  source_plan          jsonb,
  target_driver_count  integer,
  offer_count          integer,

  window_start_at      timestamptz,
  window_end_at        timestamptz,

  bonus_amount         numeric(12, 2),
  fare_multiplier      numeric(4, 2),
  estimated_cost       numeric(14, 2),

  simulation_details   jsonb,
  explanation          text,

  reviewed_by          uuid         references public.profiles (id) on delete set null,
  reviewed_at          timestamptz,
  review_note          text,

  created_at           timestamptz  not null default now(),
  updated_at           timestamptz  not null default now()
);

comment on table public.proposals is
  'Mỗi row là MỘT PHIÊN BẢN phương án. Không ghi đè proposal đã duyệt — tạo version mới.';

create index idx_proposals_hotspot on public.proposals (hotspot_id);
create index idx_proposals_status  on public.proposals (status, created_at desc);
create index idx_proposals_root    on public.proposals (root_proposal_id, version desc);

-- 7. campaigns ---------------------------------------------------------------
create table public.campaigns (
  id                   uuid         primary key default gen_random_uuid(),
  proposal_id          uuid         not null references public.proposals (id),
  -- Spec chỉ nêu TARGET_REACHED ("chỉ dừng tuyển, không tự kết thúc campaign"),
  -- không liệt kê đủ vòng đời => chưa đặt CHECK.
  status               varchar(30),

  target_h3_indexes    text[],
  geofence             geography(Polygon, 4326),
  navigation_target    geography(Point, 4326),

  target_driver_count  integer,
  batch_size           integer,

  start_at             timestamptz,
  end_at               timestamptz,
  reward_cutoff_at     timestamptz,

  bonus_amount         numeric(12, 2),
  fare_multiplier      numeric(4, 2),
  budget_limit         numeric(14, 2),
  budget_used          numeric(14, 2),

  created_by           uuid         references public.profiles (id) on delete set null,
  completed_at         timestamptz,
  created_at           timestamptz  not null default now(),
  updated_at           timestamptz  not null default now()
);

comment on table public.campaigns is
  'Bản triển khai được khoá từ proposal đã duyệt. TARGET_REACHED chỉ dừng tuyển thêm tài xế.';

create index idx_campaigns_status   on public.campaigns (status, start_at desc);
create index idx_campaigns_proposal on public.campaigns (proposal_id);
create index idx_campaigns_geofence on public.campaigns using gist (geofence);
create index idx_campaigns_h3       on public.campaigns using gin (target_h3_indexes);

-- =============================================================================
-- NHÓM 4 — Huy động, GPS và chuyến
-- =============================================================================

-- 8. driver_offers -----------------------------------------------------------
create table public.driver_offers (
  id            uuid        primary key default gen_random_uuid(),
  campaign_id   uuid        not null references public.campaigns (id) on delete cascade,
  driver_id     uuid        not null references public.profiles (id) on delete cascade,
  batch_no      integer,
  -- Spec §5.1 liệt kê đúng năm trạng thái funnel: sent/viewed/accepted/declined/expired.
  status        varchar(20) not null
                  check (status in ('SENT', 'VIEWED', 'ACCEPTED', 'DECLINED', 'EXPIRED')),
  distance_m    integer,
  eta_seconds   integer,
  sent_at       timestamptz,
  viewed_at     timestamptz,
  responded_at  timestamptz,
  expires_at    timestamptz,
  created_at    timestamptz not null default now(),
  -- Spec §4.4: "chống gửi trùng".
  constraint uq_driver_offers_campaign_driver unique (campaign_id, driver_id)
);

comment on table public.driver_offers is
  'Lời mời cá nhân gửi tài xế; tách khỏi trạng thái di chuyển (xem campaign_participations).';

create index idx_offers_driver_open on public.driver_offers (driver_id, sent_at desc)
  where status in ('SENT', 'VIEWED');
create index idx_offers_campaign    on public.driver_offers (campaign_id, batch_no, status);
create index idx_offers_expiring    on public.driver_offers (expires_at)
  where status in ('SENT', 'VIEWED');

-- 9. campaign_participations -------------------------------------------------
create table public.campaign_participations (
  id                    uuid        primary key default gen_random_uuid(),
  campaign_id           uuid        not null references public.campaigns (id) on delete cascade,
  driver_id             uuid        not null references public.profiles (id) on delete cascade,
  offer_id              uuid        references public.driver_offers (id) on delete set null,

  -- Spec §4.4 nêu bốn mốc "accepted, en-route, verified, activated" và hai tình
  -- huống hỏng "no-show / location lost"; §5.2 xác nhận tên EN_ROUTE /
  -- ARRIVED_VERIFIED / ACTIVATED.
  status                varchar(20) not null
                          check (status in ('ACCEPTED', 'EN_ROUTE', 'ARRIVED_VERIFIED',
                                            'ACTIVATED', 'NO_SHOW', 'LOCATION_LOST')),
  eligibility_status    varchar(30),

  slot_deadline_at      timestamptz,
  arrival_deadline_at   timestamptz,

  accepted_at           timestamptz,
  en_route_at           timestamptz,
  arrived_verified_at   timestamptz,
  activated_at          timestamptz,

  first_inside_at       timestamptz,
  dwell_seconds         integer,
  last_location         geography(Point, 4326),
  last_h3_index         varchar(20),
  route                 jsonb,

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  -- Hệ quả của "chống gửi trùng" trên driver_offers: mỗi tài xế tối đa một
  -- lượt tham gia cho mỗi campaign.
  constraint uq_participation_campaign_driver unique (campaign_id, driver_id)
);

comment on table public.campaign_participations is
  'Slot và quá trình tài xế tới vùng. Tạo khi offer được chấp nhận.';

create index idx_participations_driver   on public.campaign_participations (driver_id, created_at desc);
create index idx_participations_campaign on public.campaign_participations (campaign_id, status);
create index idx_participations_deadline on public.campaign_participations (arrival_deadline_at)
  where status in ('ACCEPTED', 'EN_ROUTE');

-- 10. trips ------------------------------------------------------------------
create table public.trips (
  id                uuid         primary key default gen_random_uuid(),
  -- Spec §4.4: idempotency_key phục vụ "chống trùng".
  idempotency_key   varchar(120) not null unique,
  driver_id         uuid         not null references public.profiles (id) on delete cascade,
  campaign_id       uuid         references public.campaigns (id) on delete set null,
  participation_id  uuid         references public.campaign_participations (id) on delete set null,

  pickup_location   geography(Point, 4326),
  pickup_h3_index   varchar(20),
  dropoff_location  geography(Point, 4326),
  dropoff_h3_index  varchar(20),

  requested_at      timestamptz,
  pickup_at         timestamptz,
  dropoff_at        timestamptz,

  status            varchar(30),
  base_fare         numeric(12, 2),
  source            varchar(30),
  created_at        timestamptz  not null default now()
);

comment on table public.trips is
  'Chuyến mô phỏng/đồng bộ để xét thưởng vùng. idempotency_key chống ghi trùng.';

create index idx_trips_driver   on public.trips (driver_id, pickup_at desc);
create index idx_trips_campaign on public.trips (campaign_id) where campaign_id is not null;

-- 11. driver_states ----------------------------------------------------------
-- Đặt sau trips/campaigns vì tham chiếu cả hai.
create table public.driver_states (
  driver_id             uuid         primary key references public.profiles (id) on delete cascade,
  is_online             boolean,
  -- Spec mô tả "trạng thái online/rảnh" bằng lời, không nêu mã => chưa CHECK.
  operational_status    varchar(30),
  current_location      geography(Point, 4326),
  current_h3_index      varchar(20),
  active_campaign_id    uuid         references public.campaigns (id) on delete set null,
  active_trip_id        uuid         references public.trips (id) on delete set null,
  location_accuracy_m   numeric(6, 2),
  location_source       varchar(20),
  location_updated_at   timestamptz,
  updated_at            timestamptz  not null default now()
);

comment on table public.driver_states is
  'Giữ ĐÚNG MỘT trạng thái mới nhất cho mỗi tài xế — update thay vì insert liên tục.';

-- Phục vụ "tìm tài xế online/rảnh gần vùng". Lọc theo operational_status để
-- backend tự làm, vì từ vựng trạng thái chưa chốt.
create index idx_driver_states_online   on public.driver_states (current_h3_index, operational_status)
  where is_online;
create index idx_driver_states_location on public.driver_states using gist (current_location);
create index idx_driver_states_campaign on public.driver_states (active_campaign_id)
  where active_campaign_id is not null;

-- 12. driver_location_events -------------------------------------------------
create table public.driver_location_events (
  id                   bigint      generated by default as identity primary key,
  driver_id            uuid        not null references public.profiles (id) on delete cascade,
  participation_id     uuid        references public.campaign_participations (id) on delete cascade,
  location             geography(Point, 4326) not null,
  h3_index             varchar(20),
  accuracy_m           numeric(6, 2),
  source               varchar(20),
  recorded_at          timestamptz not null,
  is_inside_geofence   boolean,
  is_valid             boolean,
  event_type           varchar(30),
  created_at           timestamptz not null default now()
);

comment on table public.driver_location_events is
  'Điểm GPS tối thiểu phục vụ xác minh geofence. Retention khuyến nghị 3–7 ngày.';

create index idx_location_events_driver        on public.driver_location_events (driver_id, recorded_at desc);
create index idx_location_events_participation on public.driver_location_events (participation_id, recorded_at desc)
  where participation_id is not null;
create index idx_location_events_geo           on public.driver_location_events using gist (location);
-- Phục vụ job dọn dữ liệu theo retention.
create index idx_location_events_recorded_at   on public.driver_location_events (recorded_at);

-- =============================================================================
-- NHÓM 5 — Thưởng và audit
-- =============================================================================

-- 13. reward_records ---------------------------------------------------------
create table public.reward_records (
  id                bigint       generated by default as identity primary key,
  -- Spec §4.5: idempotency_key phục vụ "chống trùng".
  idempotency_key   varchar(120) not null unique,
  campaign_id       uuid         references public.campaigns (id) on delete set null,
  driver_id         uuid         not null references public.profiles (id) on delete cascade,
  participation_id  uuid         references public.campaign_participations (id) on delete set null,
  trip_id           uuid         references public.trips (id) on delete set null,
  -- Spec mô tả hai loại thưởng bằng lời, không nêu mã => chưa CHECK.
  reward_type       varchar(30),
  amount            numeric(12, 2),
  status            varchar(30),
  reason            text,
  qualified_at      timestamptz,
  paid_at           timestamptz,
  created_at        timestamptz  not null default now(),
  -- Spec §4.5: thưởng gắn với "participation HOẶC trip".
  constraint chk_reward_source check (participation_id is not null or trip_id is not null)
);

comment on table public.reward_records is
  'Ledger thưởng điều chuyển và thưởng theo chuyến. idempotency_key chống tính thưởng trùng.';

create index idx_rewards_driver   on public.reward_records (driver_id, created_at desc);
create index idx_rewards_campaign on public.reward_records (campaign_id, status);

-- 14. audit_logs -------------------------------------------------------------
create table public.audit_logs (
  id           bigint      generated by default as identity primary key,
  actor_id     uuid        references public.profiles (id) on delete set null,
  actor_type   varchar(20),
  entity_type  varchar(50) not null,
  entity_id    text        not null,
  action       varchar(50) not null,
  before_data  jsonb,
  after_data   jsonb,
  metadata     jsonb,
  created_at   timestamptz not null default now()
);

comment on table public.audit_logs is
  'Quyết định và thay đổi quan trọng. KHÔNG audit mọi điểm GPS.';

create index idx_audit_entity on public.audit_logs (entity_type, entity_id, created_at desc);
create index idx_audit_actor  on public.audit_logs (actor_id, created_at desc);

-- =============================================================================
-- NHÓM 6 — Tích hợp Model
-- DDL dưới đây chép nguyên từ Phụ lục A của spec (chỉ đổi bigserial -> identity
-- và thêm tiền tố schema).
-- =============================================================================

-- 15. model_inputs -----------------------------------------------------------
create table public.model_inputs (
  id                  uuid        primary key default gen_random_uuid(),
  source_snapshot_id  bigint      references public.supply_demand_snapshots (id),
  snapshot_time       timestamptz not null,
  input_payload       jsonb       not null,
  status              varchar(30) not null default 'PENDING'
                        check (status in ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  error_message       text,
  sent_at             timestamptz,
  created_at          timestamptz not null default now()
);

comment on table public.model_inputs is
  'Payload thực tế đã gửi sang Model tại một chu kỳ 5 phút. Phục vụ replay/debug/audit.';

create index idx_model_inputs_snapshot_time on public.model_inputs (snapshot_time desc);

-- 16. model_outputs ----------------------------------------------------------
create table public.model_outputs (
  id                 uuid         primary key default gen_random_uuid(),
  model_input_id     uuid         not null references public.model_inputs (id) on delete cascade,
  model_version      varchar(100) not null,
  horizon_min        smallint     not null check (horizon_min in (15, 30)),
  forecast_time      timestamptz  not null,
  regime             varchar(30)  check (regime in ('normal', 'peak', 'rain', 'rain_peak')),
  output_payload     jsonb        not null,
  processing_status  varchar(30)  not null default 'RECEIVED'
                       check (processing_status in ('RECEIVED', 'ANALYZED', 'PROPOSAL_CREATED',
                                                    'REJECTED', 'FAILED')),
  proposal_id        uuid         references public.proposals (id),
  error_message      text,
  processed_at       timestamptz,
  created_at         timestamptz  not null default now(),
  unique (model_input_id, horizon_min, model_version)
);

comment on table public.model_outputs is
  'Kết quả Model theo horizon t+15/t+30. UI lấy bản ghi mới nhất theo horizon_min.';

create index idx_model_outputs_latest on public.model_outputs (horizon_min, forecast_time desc);

-- =============================================================================
-- Khoá ngoại đi ngược chiều tạo bảng
-- =============================================================================

alter table public.supply_demand_cells
  add constraint fk_sd_cells_active_campaign
  foreign key (active_campaign_id) references public.campaigns (id) on delete set null;

create index idx_sd_cells_active_campaign on public.supply_demand_cells (active_campaign_id)
  where active_campaign_id is not null;

-- =============================================================================
-- Trigger updated_at
-- =============================================================================

create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger trg_proposals_updated_at
  before update on public.proposals
  for each row execute function public.set_updated_at();

create trigger trg_campaigns_updated_at
  before update on public.campaigns
  for each row execute function public.set_updated_at();

create trigger trg_participations_updated_at
  before update on public.campaign_participations
  for each row execute function public.set_updated_at();

create trigger trg_driver_states_updated_at
  before update on public.driver_states
  for each row execute function public.set_updated_at();

-- =============================================================================
-- Đồng bộ auth.users -> profiles
--
-- Spec §4.1: profiles là "hồ sơ mở rộng từ Supabase Auth". Trigger này là phần
-- nối kỹ thuật để bản ghi profiles tồn tại ngay khi có user; spec không mô tả
-- cơ chế nên phần lấy role từ user metadata là quy ước của nhóm, sửa được.
-- =============================================================================

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, role, full_name, phone)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'DRIVER'),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'phone', ''), new.phone)
  )
  on conflict (id) do nothing;

  return new;
end
$$;

comment on function public.handle_new_auth_user() is
  'Tạo bản ghi profiles tương ứng mỗi khi auth.users có user mới. role lấy từ user metadata, mặc định DRIVER.';

create trigger trg_on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();
